# Generated by Django 4.2.7 on 2023-11-17 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedInApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
